Models/ChiNhanh.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiNhanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiNhanh()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.Menus = new HashSet<Menu>();
            this.NhanViens = new HashSet<NhanVien>();
            this.NhanViens1 = new HashSet<NhanVien>();
            this.Menus1 = new HashSet<Menu>();
        }
    
        public string MaChiNhanh { get; set; }
        public string TenChiNhanh { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus1 { get; set; }
    }
}

Controllers/ChiNhanhsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Doan1.Models;
using PagedList;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.Ajax.Utilities;

namespace Doan1.Controllers
{
    [AuthorizeController]
    public class ChiNhanhsController : Controller
    {
        private QuanLyCuaHangTraSuaEntities1 db = new QuanLyCuaHangTraSuaEntities1();
        [HttpGet]

        // GET: ChiNhanhs
        public ActionResult Index(int? size, int? page, string sortProperty, string sortOrder, string searchString)
        {
            // 1. Tạo biến ViewBag gồm sortOrder, searchValue, sortProperty và page
            if (sortOrder == "asc") ViewBag.sortOrder = "desc";
            if (sortOrder == "desc") ViewBag.sortOrder = "";
            if (sortOrder == "") ViewBag.sortOrder = "asc";
            ViewBag.searchValue = searchString;
            ViewBag.sortProperty = sortProperty;
            ViewBag.page = page;

            // 2. Tạo danh sách chọn số trang
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            

            // 2.1. Thiết lập số trang đang chọn vào danh sách List<SelectListItem> items
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }
            ViewBag.size = items;
            ViewBag.currentSize = size;

            // 3. Lấy tất cả tên thuộc tính của lớp chinhanhs
            var properties = typeof(ChiNhanh).GetProperties();
            List<Tuple<string, bool, int>> list = new List<Tuple<string, bool, int>>();
            foreach (var item in properties)
            {
                int order = 999;
                var isVirtual = item.GetAccessors()[0].IsVirtual;

                if (item.Name == "TenChiNhanh") order = 2;
                if (item.Name == "MaChiNhanh") order = 1;
                if (item.Name == "DiaChi") continue;
                if (item.Name == "NhanViens") continue;
                if (item.Name == "HoaDons") continue;
                if (item.Name == "Menus") continue;

                Tuple<string, bool, int> t = new Tuple<string, bool, int>(item.Name, isVirtual, order);
                list.Add(t);
            }
            list = list.OrderBy(x => x.Item3).ToList();

            // 3.1. Tạo Heading sắp xếp cho các cột
            foreach (var item in list)
            {
                if (!item.Item2)
                {
                    if (sortOrder == "desc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                            ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-desc'></i></th></a></th>";
                    }
                    else if (sortOrder == "asc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                            ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-asc'></a></th>";
                    }
                    else
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                           ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort'></a></th>";
                    }

                }
                else ViewBag.Headings += "<th>" + item.Item1 + "</th>";
            }

            // 4. Truy vấn lấy tất cả đường dẫn
            var chinhanh = from l in db.ChiNhanhs
                           select l;

            // 5. Tạo thuộc tính sắp xếp mặc định là "MaMon"
            if (String.IsNullOrEmpty(sortProperty)) sortProperty = "MaChiNhanh";

            // 5. Sắp xếp tăng/giảm bằng phương thức OrderBy sử dụng trong thư viện Dynamic LINQ
            if (sortOrder == "desc") chinhanh = chinhanh.OrderBy(sortProperty + " desc");
            else if (sortOrder == "asc") chinhanh = chinhanh.OrderBy(sortProperty);
            else chinhanh = chinhanh.OrderBy("MaChiNhanh");

            // 5.1. Thêm phần tìm kiếm
            if (!String.IsNullOrEmpty(searchString))
            {
                chinhanh = chinhanh.Where(s => s.TenChiNhanh.Contains(searchString));
            }

            // 5.2. Nếu page = null thì đặt lại là 1.
            page = page ?? 1; //if (page == null) page = 1;

            // 5.3. Tạo kích thước trang (pageSize), mặc định là 5.
            int pageSize = (size ?? 5);

            ViewBag.pageSize = pageSize;

            // 6. Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber. --- dammio.com
            int pageNumber = (page ?? 1);

            // 6.2 Lấy tổng số record chia cho kích thước để biết bao nhiêu trang
            int checkTotal = (int)(chinhanh.ToList().Count / pageSize) + 1;
            // Nếu trang vượt qua tổng số trang thì thiết lập là 1 hoặc tổng số trang
            if (pageNumber > checkTotal) pageNumber = checkTotal;

            // 7. Trả về các chinhanh được phân trang theo kích thước và số trang.
            return View(chinhanh.ToPagedList(pageNumber, pageSize));
        }

        // GET: ChiNhanhs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiNhanh chiNhanh = db.ChiNhanhs.Find(id);
            if (chiNhanh == null)
            {
                return HttpNotFound();
            }
            return View(chiNhanh);
        }
        [AuthorizeController]
        // GET: ChiNhanhs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChiNhanhs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeController]
        public ActionResult Create([Bind(Include = "MaChiNhanh,TenChiNhanh,DiaChi")] ChiNhanh chiNhanh)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    chiNhanh.MaChiNhanh = (db.ChiNhanhs.Count() + 1).ToString();
                    db.ChiNhanhs.Add(chiNhanh);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(chiNhanh);
            }
            catch
            {
                Session["Check"] = "Mã Chi Nhánh Đã Tồn Tại";
                return RedirectToAction("Create");
            }
        }

        // GET: ChiNhanhs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiNhanh chiNhanh = db.ChiNhanhs.Find(id);
            if (chiNhanh == null)
            {
                return HttpNotFound();
            }
            return View(chiNhanh);
        }

        // POST: ChiNhanhs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaChiNhanh,TenChiNhanh,DiaChi")] ChiNhanh chiNhanh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chiNhanh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chiNhanh);
        }

        // GET: ChiNhanhs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiNhanh chiNhanh = db.ChiNhanhs.Find(id);
            if (chiNhanh == null)
            {
                return HttpNotFound();
            }
            return View(chiNhanh);
        }

        // POST: ChiNhanhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ChiNhanh chiNhanh = db.ChiNhanhs.Find(id);
            db.ChiNhanhs.Remove(chiNhanh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
       
    }
}

Views/ChiNhanhs/Create.cshtml
@model Doan1.Models.ChiNhanh

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Thêm Chi Nhánh</h2>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    string err = (string)Session["Check"];
    if (err != null)
    {
        <lable style=" text-align: center" class="text-danger">@err</lable>
        Session.Remove("Check");
    }
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Mã Chi Nhánh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaChiNhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaChiNhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tên Chi Nhánh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChiNhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenChiNhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Địa Chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/ChiNhanhs/Index'" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ChiNhanhs/Delete.cshtml
@model Doan1.Models.ChiNhanh

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Xóa Chi Nhánh</h2>
</div>
<div>
    <h4>Chi Nhánh</h4>
    <hr />
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Mã Chi Nhánh</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.MaChiNhanh, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.MaChiNhanh)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Tên Chi Nhánh</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.TenChiNhanh, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.TenChiNhanh)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Địa Chỉ</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.DiaChi)
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="delete" value="Delete" class="btn btn-danger" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/ChiNhanhs/Index'" />
            </div>
        </div>
    }
</div>

Views/ChiNhanhs/Details.cshtml
@model Doan1.Models.ChiNhanh

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Chi tiết thông tin Chi Nhánh</h2>
</div>
<div>
    <h4>Chi Nhánh</h4>
    <hr />
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Mã Chi Nhánh</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.MaChiNhanh, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.MaChiNhanh)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Tên Chi Nhánh</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.TenChiNhanh, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.TenChiNhanh)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Địa Chỉ</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.DiaChi)
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/ChiNhanhs/Index'" />
        </div>
    </div>

</div>

Views/ChiNhanhs/Edit.cshtml
@model Doan1.Models.ChiNhanh

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Chỉnh Sửa Thông Tin Chi Nhánh</h2>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaChiNhanh)

        <div class="form-group">
            <label class="control-label col-md-2">Tên Chi Nhánh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChiNhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenChiNhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Địa Chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/ChiNhanhs/Index'" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ChiNhanhs/Index.cshtml
@model PagedList.IPagedList<Doan1.Models.ChiNhanh>
@using Doan1.Models;
@using System.Linq;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table {
        background-color: aliceblue;
    }
</style>

<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Thông Tin Chi Nhánh</h2>
</div>
@using (Html.BeginForm("Index", "ChiNhanhs", FormMethod.Get))
{
    <p>
        Tên Chi Nhánh: @Html.TextBox("SearchString", (string)ViewBag.searchValue) <input type="submit" value="Tìm kiếm" /> <input type="button" onclick="location.href = '/ChiNhanhs/Index'" name="Reset" value="Mặc định" />
        @Html.Hidden("page", (object)ViewBag.page)
        @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
        @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
        @Html.Hidden("size", (object)ViewBag.pageSize)
    </p>
}
<p>
    <input type="button" class="btn btn-danger" onclick="location.href = '/ChiNhanhs/Create'" value="Thêm Chi Nhánh mới" />
</p>


<table class="table">

    @Html.Raw(ViewBag.Headings)


    <tr style="background-color:Highlight; text-align:center">



        <th>
            <div>Tên Chi Nhánh</div>
        </th>
        <th>
            <div>Địa Chỉ</div>
        </th>
        <th></th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.TenChiNhanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaChiNhanh }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaChiNhanh }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaChiNhanh })
            </td>
        </tr>
    }
</table>

<!-- Thêm mã phân trang -->
<br />

<div style="text-align: center">
    @using (Html.BeginForm("Index", "ChiNhanhs", FormMethod.Get))
    {
        <p>
            Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
        </p>

        @Html.Hidden("page", (object)ViewBag.page)
        @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
        @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
        @Html.Hidden("searchString", (object)ViewBag.searchValue)
    }
</div>
<div style="text-align: center">
    <br />
    Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
</div>

<div style="text-align: center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, size = ViewBag.currentSize, sortProperty = ViewBag.sortProperty, sortOrder = ViewBag.SortOrder, searchString = ViewBag.searchValue }))
</div>
<!-- Kết thúc -->