Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Doan1.Models
{
    public class GioHang
    {
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string Size { get; set; }
        public int SoLuong { get; set; }
        public double Gia { get; set; }
        public double ThanhTien { get; set; }
        public string Duong { get; set; }
        public string Da { get; set; }
        public string Anh { get; set; }
        public GioHang(string iMaMon,string size,string duong,string da,int sl,string anh)
        {
            using (QuanLyCuaHangTraSuaEntities1 db = new QuanLyCuaHangTraSuaEntities1())
            {
                this.MaMon = iMaMon;
                Menu mn = db.Menus.Single(n => n.MaMon == iMaMon);
                this.TenMon = mn.TenMon;
                this.Gia = mn.GiaTien;
                this.SoLuong = sl;
                this.ThanhTien = Gia * SoLuong;
                this.Duong = duong;
                this.Da = da;
                this.Size = size;
                this.Anh = anh;
            }
        }

       
        public GioHang()
        {
            using (QuanLyCuaHangTraSuaEntities1 db = new QuanLyCuaHangTraSuaEntities1())
            {
                this.MaMon = "";
                this.TenMon ="";
                this.Gia = 0;
                this.SoLuong = 0;
                this.ThanhTien = Gia * SoLuong;
                this.Duong = "";
                this.Da = "";
                this.Size = "";
                this.Anh = "";
            }
        }

    }
}

Models/Menu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.ChiTietHoaDons1 = new HashSet<ChiTietHoaDon>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string Loai { get; set; }
        public double GiaTien { get; set; }
        public string MaChiNhanh { get; set; }
        public string AnhMinhHoa { get; set; }
        public int SoLuongDaBan { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual ChiNhanh ChiNhanh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons1 { get; set; }
    }
}

Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Doan1.Models;
using PagedList;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.Ajax.Utilities;
using EPPlusTest;
using OfficeOpenXml;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Configuration;
using Doan1.Models.Factory_Method;
using Microsoft.AspNetCore.Hosting;
using Firebase.Auth;
using System.Threading;
using Firebase.Storage;
using System.Threading.Tasks;
using System.Diagnostics;
using PayPal.Api;
namespace Doan1.Controllers
{
    public class MenusController : Controller
    {
        private QuanLyCuaHangTraSuaEntities1 db = new QuanLyCuaHangTraSuaEntities1();
        // GET: Menus
        public string err = "";
        static private string idtrans;
        public static int soluong;
        public class HttpParamActionAttribute : ActionNameSelectorAttribute
        {
            public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo)
            {
                if (actionName.Equals(methodInfo.Name, StringComparison.InvariantCultureIgnoreCase))
                    return true;

                var request = controllerContext.RequestContext.HttpContext.Request;
                return request[methodInfo.Name] != null;
            }
        }
        [AuthorizeController]
        [HttpGet]
        // GET: 
        public ActionResult Index(int? size, int? page, string sortProperty, string sortOrder, string searchString)
        {

            // 1. Tạo biến ViewBag gồm sortOrder, searchValue, sortProperty và page
            if (sortOrder == "asc") ViewBag.sortOrder = "desc";
            if (sortOrder == "desc") ViewBag.sortOrder = "";
            if (sortOrder == "") ViewBag.sortOrder = "asc";
            ViewBag.searchValue = searchString;
            ViewBag.sortProperty = sortProperty;
            ViewBag.page = page;

            // 2. Tạo danh sách chọn số trang
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });


            // 2.1. Thiết lập số trang đang chọn vào danh sách List<SelectListItem> items
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }
            ViewBag.size = items;
            ViewBag.currentSize = size;

            // 3. Lấy tất cả tên thuộc tính của lớp Menu (MaMon, TenMon, Loai,...)
            var properties = typeof(Menu).GetProperties();
            List<Tuple<string, bool, int>> list = new List<Tuple<string, bool, int>>();
            foreach (var item in properties)
            {
                int order = 999;
                var isVirtual = item.GetAccessors()[0].IsVirtual;

                if (item.Name == "TenMon")
                {
                    order = 2;
                }
                if (item.Name == "MaMon") order = 1;
                if (item.Name == "Loai") order = 3;
                if (item.Name == "GiaTien") order = 4;
                if (item.Name == "MaChiNhanh") continue; // Không hiển thị cột này
                if (item.Name == "ChiNhanh") continue;
                if (item.Name == "SoLuongDaBan") order = 5;
                if (item.Name == "AnhMinhHoa") continue; // Không hiển thị cột này
                if (item.Name == "ChiTietHoaDons") continue;
                if (item.Name == "ChiTietHoaDons1") continue;
                if (item.Name == "ChiNhanh1") continue;

                Tuple<string, bool, int> t = new Tuple<string, bool, int>(item.Name, isVirtual, order);
                list.Add(t);
            }
            list = list.OrderBy(x => x.Item3).ToList();

            // 3.1. Tạo Heading sắp xếp cho các cột
            foreach (var item in list)
            {
                if (!item.Item2)
                {
                    if (sortOrder == "desc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                            ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-desc'></i></th></a></th>";
                    }
                    else if (sortOrder == "asc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                            ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-asc'></a></th>";
                    }
                    else
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                           ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort'></a></th>";
                    }

                }
                else ViewBag.Headings += "<th>" + item.Item1 + "</th>";
            }

            // 4. Truy vấn lấy tất cả đường dẫn
            var menu = from l in db.Menus
                       select l;

            // 5. Tạo thuộc tính sắp xếp mặc định là "MaMon"
            if (String.IsNullOrEmpty(sortProperty)) sortProperty = "MaMon";

            // 5. Sắp xếp tăng/giảm bằng phương thức OrderBy sử dụng trong thư viện Dynamic LINQ
            if (sortOrder == "desc") menu = menu.OrderBy(sortProperty + " desc");
            else if (sortOrder == "asc") menu = menu.OrderBy(sortProperty);
            else menu = menu.OrderBy("MaMon");

            // 5.1. Thêm phần tìm kiếm
            if (!String.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.TenMon.Contains(searchString));
            }

            // 5.2. Nếu page = null thì đặt lại là 1.
            page = page ?? 1; //if (page == null) page = 1;

            // 5.3. Tạo kích thước trang (pageSize), mặc định là 5.
            int pageSize = (size ?? 5);

            ViewBag.pageSize = pageSize;

            // 6. Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber. --- dammio.com
            int pageNumber = (page ?? 1);

            // 6.2 Lấy tổng số record chia cho kích thước để biết bao nhiêu trang
            int checkTotal = (int)(menu.ToList().Count / pageSize) + 1;
            // Nếu trang vượt qua tổng số trang thì thiết lập là 1 hoặc tổng số trang
            if (pageNumber > checkTotal) pageNumber = checkTotal;

            // 7. Trả về các menu được phân trang theo kích thước và số trang.
            return View(menu.ToPagedList(pageNumber, pageSize));
        }

        public void Xuat()
        {
            var a = from l in db.Menus
                    select l;
            var list = a.ToList();
            list = list.OrderBy(s => s.Loai).ToList();
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
            Sheet.Cells["A1"].Value = "Mã món";
            Sheet.Cells["B1"].Value = "Tên món";
            Sheet.Cells["C1"].Value = "Loại";
            Sheet.Cells["D1"].Value = "Giá tiền";
            Sheet.Cells["E1"].Value = "Tên Chi Nhánh";
            Sheet.Cells["F1"].Value = "Link Ảnh";
            Sheet.Cells["G1"].Value = "Đã bán";
            int row = 2;

            foreach (var item in list)
            {
                Sheet.Cells[string.Format("A{0}", row)].Value = item.MaMon;
                Sheet.Cells[string.Format("B{0}", row)].Value = item.TenMon;
                Sheet.Cells[string.Format("C{0}", row)].Value = item.Loai;
                Sheet.Cells[string.Format("D{0}", row)].Value = item.GiaTien;
                Sheet.Cells[string.Format("E{0}", row)].Value = item.ChiNhanh.TenChiNhanh;
                Sheet.Cells[string.Format("F{0}", row)].Value = item.AnhMinhHoa;
                Sheet.Cells[string.Format("G{0}", row)].Value = item.SoLuongDaBan;
                row++;
            }


            Sheet.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "Report.xlsx");
            Response.BinaryWrite(Ep.GetAsByteArray());
            Response.End();
        }


        // GET: Menus/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }
        [AuthorizeController]

        // GET: Menus/Create
        public ActionResult Create()
        {
            ViewBag.MaChiNhanh = new SelectList(db.ChiNhanhs, "MaChiNhanh", "TenChiNhanh");

            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //   [AuthorizeController]

Views/Menus/Create.cshtml
@model Doan1.Models.Menu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron"></div>
<div class="jumbotron">
    <h2 style=" text-align: center" class="text-info">Thêm Sản Phẩm</h2>
</div>
@using (Html.BeginForm("Create", "Menus", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    string err = (string)Session["Check"];
    if (err != null)
    {
        <lable style=" text-align: center" class="text-danger">@err</lable>
        Session.Remove("Check");
    }
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tên Món</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Loại</label>
            <div class="col-md-10">
                <select class="form-control-lg" name="Loai">
                    <option>Trà Sữa</option>
                    <option>Trà</option>
                    <option>Món Khác</option> 

                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Giá Tiền</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi Nhánh</label>
            <div class="col-md-10">
                @Html.DropDownList("MaChiNhanh", null, htmlAttributes: new { @class = "form-control-lg" })
                @Html.ValidationMessageFor(model => model.MaChiNhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh minh họa</label>
            <div class="col-md-10">
                <fieldset>
                    <p>
                        <input type="file" name="postedFile" class="col-2" />
                    </p>
                </fieldset>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="add" value="Create" class="btn btn-success" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/Menus/Index'" />
            </div>
        </div>
    </div>
}

@section scripts{

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>


    @Scripts.Render("~/bundles/jqueryval")

}

Views/Menus/Delete.cshtml
@model Doan1.Models.Menu

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="padding-top:6em"></div>
<div class="jumbotron">
    <h2 style=" text-align: center" class="text-danger">Xóa Sản Phẩm</h2>
</div>
<div>
    <h4>Menu</h4>
    <hr />
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Mã Món</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.MaMon, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.MaMon)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2"> <b>Tên Món</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.DisplayFor(model => model.TenMon)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2"> <b>Loại</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.Loai, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.DisplayFor(model => model.Loai)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2"> <b>Giá Tiền</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.GiaTien, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.DisplayFor(model => model.GiaTien)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2"> <b>Tên Chi Nhánh</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.ChiNhanh.TenChiNhanh, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.DisplayFor(model => model.ChiNhanh.TenChiNhanh)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2"> <b>Ảnh Minh Họa</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.AnhMinhHoa, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.DisplayFor(model => model.AnhMinhHoa)
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="delete" value="Delete" class="btn btn-danger" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/Menus/Index'" />
            </div>
        </div>
    }



</div>

Views/Menus/Edit.cshtml
@model Doan1.Models.Menu
@using Doan1.Models
@using System.Linq;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style=" text-align: center" class="text-info">Chỉnh Sửa Món</h2>
</div>


@using (Html.BeginForm("Edit", "Menus", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaMon)
        @Html.HiddenFor(model => model.AnhMinhHoa)
        <div class="form-group">
            <label class="control-label col-md-2"><b>Tên Món</b></label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Loại</label>
            <div class="col-md-10">
                <select class="form-control-lg" name="Loai">
                    @if (Model.Loai == "Trà Sữa")
                    {
                        <option selected>Trà Sữa</option>
                        <option>Trà</option>
                        <option>Món Khác</option>
                    }
                    else if (Model.Loai == "Trà")
                    {
                        <option>Trà Sữa</option>
                        <option selected>Trà</option>
                        <option>Món Khác</option>
                    }
                    else if (Model.Loai == "Món Khác")
                    {
                        <option>Trà Sữa</option>
                        <option>Trà</option>
                        <option selected>Món Khác</option>
                    }

                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"><b>Giá Tiền</b></label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi Nhánh</label>
            <div class="col-md-10">
                @Html.DropDownList("MaChiNhanh", null, htmlAttributes: new { @class = "form-control-lg" })
                @Html.ValidationMessageFor(model => model.MaChiNhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"><b>Ảnh minh họa</b></label>
            <div class="col-md-10">
                <div style="width:200px;height:100px;">
                    @Html.Image(Url.Content(Model.AnhMinhHoa), "alt", "100", "100")
                </div>
                <fieldset>
                    <p>
                        <input type="file" name="postedFile" class="col-2" />
                    </p>
                </fieldset>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/Menus/Index'" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Menus/Index.cshtml
@using Doan1.Models;
@using System.Linq;
@model PagedList.IPagedList<Doan1.Models.Menu>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>


<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger"> Menu Sản Phẩm</h2>
</div>
@using (Html.BeginForm("Index", "Menus", FormMethod.Get))
{
    <p>
        Tên món: @Html.TextBox("SearchString", (string)ViewBag.searchValue) <input type="submit" value="Tìm kiếm" /> <input type="button" onclick="location.href = '/Menus/Index'" name="Reset" value="Mặc định" />
        @Html.Hidden("page", (object)ViewBag.page)
        @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
        @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
        @Html.Hidden("size", (object)ViewBag.pageSize)
    </p>
}
<p>
    <input type="button" class="btn btn-danger" onclick="location.href = '/Menus/Create'" value="Tạo món mới" />
</p>

<table class="table">
    <tr>

        @Html.Raw(ViewBag.Headings)

    <tr style="background-color:Highlight; text-align:center">

        <th>
            <div>Mã Món</div>
        </th>

        <th>
            <div>Tên Món</div>
        </th>
        <th>
            <div>Loại</div>
        </th>
        <th>
            <div>Giá Tiền</div>
        </th>
        <th>
            <div>Đã bán</div>
        </th>
        <th>
            <div>Chi Nhánh</div>
        </th>
        <th>
            <div>Ảnh</div>
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.MaMon)

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TenMon)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Loai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaTien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongDaBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChiNhanh.TenChiNhanh)
            </td>
            <td>
                <div style="width:200px;height:100px;">
                    @Html.Image(Url.Content(item.AnhMinhHoa), "alt", "100", "100")
                </div>
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaMon }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaMon }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaMon })
            </td>
        </tr>
    }

</table>
<div class="col-2">
    <a href="@Url.Action("Xuat")">Tải về Excel</a>
</div>
<fieldset>

    @using (Html.BeginForm("ImportFromExcel", "Menus", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary();
        <p>
            <input type="file" name="postedFile" class="col-2" />
        </p>
        <p class="col-2">
            <input type="submit" button id="upload" value="Import" class="btn-success" />
        </p>
    }

</fieldset>
@section scripts{

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <script>
        $("#upload").click(function () {
            debugger;
            if (window.FormData == undefined)
                alert("Error: FormData is undefined");

            else {
                var fileUpload = $("#postedFile").get(0);
                var files = fileUpload.files;

                var fileData = new FormData();

                fileData.append(files[0].name, files[0]);

                $.ajax({
                    url: '/Menus/ImportFromExcel',
                    type: 'post',
                    datatype: 'json',
                    contentType: false,
                    processData: false,
                    async: false,
                    data: fileData,
                    success: function (response) {
                        alert(response);
                    }
                });
            }

        });
    </script>

}

<!-- Thêm mã phân trang -->
<br />

<div style="text-align: center">
    @using (Html.BeginForm("Index", "Menus", FormMethod.Get))
    {
        <p>
            Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
        </p>

        @Html.Hidden("page", (object)ViewBag.page)
        @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
        @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
        @Html.Hidden("searchString", (object)ViewBag.searchValue)
    }
</div>
<div style="text-align: center">
    Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
</div>

<div style="text-align: center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, size = ViewBag.currentSize, sortProperty = ViewBag.sortProperty, sortOrder = ViewBag.SortOrder, searchString = ViewBag.searchValue }))
</div>
<!-- Kết thúc -->