Models/KhachHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.HoaDons1 = new HashSet<HoaDon>();
        }
    
        public string SoDienThoai { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> DaMua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons1 { get; set; }
    }
}

Controllers/KhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Doan1.Models;
using PagedList;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.Ajax.Utilities;

namespace Doan1.Controllers
{


    public class KhachHangsController : Controller
    {
        private QuanLyCuaHangTraSuaEntities1 db = new QuanLyCuaHangTraSuaEntities1();
        [HttpGet]
        [AuthorizeController]
        // GET: KhachHangs
        public ActionResult Index(int? size, int? page, string sortProperty, string sortOrder, string searchString)
        {
            // 1. Tạo biến ViewBag gồm sortOrder, searchValue, sortProperty và page
            if (sortOrder == "asc") ViewBag.sortOrder = "desc";
            if (sortOrder == "desc") ViewBag.sortOrder = "";
            if (sortOrder == "") ViewBag.sortOrder = "asc";
            ViewBag.searchValue = searchString;
            ViewBag.sortProperty = sortProperty;
            ViewBag.page = page;

            // 2. Tạo danh sách chọn số trang
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });


            // 2.1. Thiết lập số trang đang chọn vào danh sách List<SelectListItem> items
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }
            ViewBag.size = items;
            ViewBag.currentSize = size;

            // 3. Lấy tất cả tên thuộc tính của lớp khachhangs
            var properties = typeof(KhachHang).GetProperties();
            List<Tuple<string, bool, int>> list = new List<Tuple<string, bool, int>>();
            foreach (var item in properties)
            {
                int order = 999;
                var isVirtual = item.GetAccessors()[0].IsVirtual;

                if (item.Name == "TenKH") order = 2;
                if (item.Name == "SoDienThoai") order = 1;
                if (item.Name == "Email") continue;
                if (item.Name == "MatKhau") continue;
                if (item.Name == "DiaChi") continue;
                if (item.Name == "HoaDons") continue;
                if (item.Name == "HoaDons1") continue;

                Tuple<string, bool, int> t = new Tuple<string, bool, int>(item.Name, isVirtual, order);
                list.Add(t);
            }
            list = list.OrderBy(x => x.Item3).ToList();

            // 3.1. Tạo Heading sắp xếp cho các cột
            foreach (var item in list)
            {
                if (!item.Item2)
                {
                    if (sortOrder == "desc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                            ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-desc'></i></th></a></th>";
                    }
                    else if (sortOrder == "asc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                            ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-asc'></a></th>";
                    }
                    else
                    {
                        ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                           ViewBag.sortOrder + "&searchString=" + searchString + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort'></a></th>";
                    }

                }
                else ViewBag.Headings += "<th>" + item.Item1 + "</th>";
            }

            // 4. Truy vấn lấy tất cả đường dẫn
            var khachhang = from l in db.KhachHangs
                            select l;

            // 5. Tạo thuộc tính sắp xếp mặc định là "MaMon"
            if (String.IsNullOrEmpty(sortProperty)) sortProperty = "SoDienThoai";

            // 5. Sắp xếp tăng/giảm bằng phương thức OrderBy sử dụng trong thư viện Dynamic LINQ
            if (sortOrder == "desc") khachhang = khachhang.OrderBy(sortProperty + " desc");
            else if (sortOrder == "asc") khachhang = khachhang.OrderBy(sortProperty);
            else khachhang = khachhang.OrderBy("SoDienThoai");

            // 5.1. Thêm phần tìm kiếm
            if (!String.IsNullOrEmpty(searchString))
            {
                khachhang = khachhang.Where(s => s.TenKH.Contains(searchString));
            }

            // 5.2. Nếu page = null thì đặt lại là 1.
            page = page ?? 1; //if (page == null) page = 1;

            // 5.3. Tạo kích thước trang (pageSize), mặc định là 5.
            int pageSize = (size ?? 5);

            ViewBag.pageSize = pageSize;

            // 6. Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber. --- dammio.com
            int pageNumber = (page ?? 1);

            // 6.2 Lấy tổng số record chia cho kích thước để biết bao nhiêu trang
            int checkTotal = (int)(khachhang.ToList().Count / pageSize) + 1;
            // Nếu trang vượt qua tổng số trang thì thiết lập là 1 hoặc tổng số trang
            if (pageNumber > checkTotal) pageNumber = checkTotal;

            // 7. Trả về các khachhang được phân trang theo kích thước và số trang.
            return View(khachhang.ToPagedList(pageNumber, pageSize));
        }

        // GET: KhachHangs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Create
        [AuthorizeController]
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeController]
        public ActionResult Create([Bind(Include = "SoDienThoai,TenKH,DiaChi,Email,MatKhau")] KhachHang khachHang)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    khachHang.DaMua = 0;
                    db.KhachHangs.Add(khachHang);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(khachHang);
            }
            catch
            {
                Session["Check"] = "Số Điện Thoại Khách Hàng Đã Tồn Tại ";
                return RedirectToAction("Create");
            }
        }

        // GET: KhachHangs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SoDienThoai,TenKH,DiaChi,Email,MatKhau")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khachHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            KhachHang khachHang = db.KhachHangs.Find(id);
            db.KhachHangs.Remove(khachHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ThongTinKhachHang()
        {
            if ((string)Session["QuyenUser"] == "3")
            {
                string sdt = (string)Session["SDT"];
                KhachHang khachHang = db.KhachHangs.Find(sdt);
                if (khachHang == null)
                {
                    return HttpNotFound();
                }
                return View(khachHang);

            }

Views/KhachHangs/Create.cshtml
@model Doan1.Models.KhachHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div class="jumbotron"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Thêm khách hàng</h2>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    string err = (string)Session["Check"];
    if (err != null)
    {
        <lable style=" text-align: center" class="text-danger">@err</lable>
        Session.Remove("Check");
    }
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Số Điện Thoại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Tên Khách Hàng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Địa Chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mật Khẩu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/KhachHangs/Index'" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/KhachHangs/Delete.cshtml
@model Doan1.Models.KhachHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Xóa khách hàng</h2>
</div>
<div>
    <h4>Khách Hàng</h4>
    <hr />
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Số Điện Thoại</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.SoDienThoai)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Tên Khách Hàng</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.TenKH)
        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Địa Chỉ</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.DiaChi)
        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Email</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.Email)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Mật Khẩu</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.MatKhau)
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="delete" value="Delete" class="btn btn-danger" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/KhachHangs/Index'" />
            </div>
        </div>
    }
</div>

Views/KhachHangs/Details.cshtml
@model Doan1.Models.KhachHang

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Chi tiết thông tin khách hàng</h2>
</div>

<div>
    <h4>Khách Hàng</h4>
    <hr />
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Số Điện Thoại</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.SoDienThoai)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Tên Khách Hàng</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.TenKH)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Địa Chỉ</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.DiaChi)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Đã mua</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.DaMua, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.DaMua)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Email</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.Email)
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 "> <b>Mật Khẩu</b></label>
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })

        </div>

        <div>
            @Html.DisplayFor(model => model.MatKhau)
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/KhachHangs/Index'" />
        </div>
    </div>

</div>

Views/KhachHangs/Edit.cshtml
@model Doan1.Models.KhachHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table {
        background-color: aliceblue;
    }
</style>
<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Chỉnh sửa thông tin khách hàng</h2>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tên Khách Hàng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Địa Chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mật Khẩu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" id="back" value="Back" class="btn btn-info" onclick="location.href='/KhachHangs/Index'" />
            </div>
        </div>

    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/KhachHangs/Index.cshtml
@using Doan1.Models;
@using System.Linq;
@model PagedList.IPagedList<Doan1.Models.KhachHang>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table {
        background-color: aliceblue;
    }
</style>

<div style="padding-top:6em"></div>

<div class="jumbotron">
    <h2 style="text-align: center" class="text-danger">Thông Tin Khách Hàng</h2>
</div>
@using (Html.BeginForm("Index", "KhachHangs", FormMethod.Get))
{
    <p>
        Tên Khách Hàng: @Html.TextBox("SearchString", (string)ViewBag.searchValue) <input type="submit" value="Tìm kiếm" /> <input type="button" onclick="location.href = '/KhachHangs/Index'" name="Reset" value="Mặc định" />
        @Html.Hidden("page", (object)ViewBag.page)
        @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
        @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
        @Html.Hidden("size", (object)ViewBag.pageSize)
    </p>
}
<p>
    <input type="button" class="btn btn-danger" onclick="location.href = '/KhachHangs/Create'" value="Thêm Khách Hàng" />
</p>



<table class="table">

    @Html.Raw(ViewBag.Headings)


    <tr style="background-color:Highlight; text-align:center">

        <th>
            <div>Số Điện thoại</div>
        </th>

        <th>
            <div>Tên Khách Hàng</div>
        </th>
        <th>
            <div>Đã mua</div>
        </th>
        <th>
            <div>Địa Chỉ</div>
        </th>
        <th>
            <div>Email</div>
        </th>
        <th>
            <div>Mật Khẩu</div>
        </th>
        <th></th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaMua)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.SoDienThoai }) |
                @Html.ActionLink("Details", "Details", new { id = item.SoDienThoai }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.SoDienThoai })
            </td>
        </tr>
    }

</table>


<!-- Thêm mã phân trang -->
<br />

<div style="text-align: center">
    @using (Html.BeginForm("Index", "KhachHangs", FormMethod.Get))
    {
        <p>
            Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
        </p>

        @Html.Hidden("page", (object)ViewBag.page)
        @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
        @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
        @Html.Hidden("searchString", (object)ViewBag.searchValue)
    }
</div>
<div style="text-align: center">
    Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
</div>
<div style="text-align: center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, size = ViewBag.currentSize, sortProperty = ViewBag.sortProperty, sortOrder = ViewBag.SortOrder, searchString = ViewBag.searchValue }))
</div>
<!-- Kết thúc -->

Views/KhachHangs/ThongKe.cshtml
@using Doan1.Models;
@model IEnumerable<Doan1.Models.KhachHang>
@{
    ViewBag.Title = "ThongKe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="padding-top:10em"></div>
@{ int soLuongKhachHang = ViewBag.soLuongKH;
}
<body>

    <div style="background-color:transparent">
        <h2 style="text-align: center" class="text-danger"> Top 5 Khách Hàng Mua Nhiều Nhất</h2>
    </div>
    <div class="jumbotron" align="left" style="background-color:transparent">
            <font size="4" color="red">
                Tổng Số Khách Hàng:@soLuongKhachHang Người

            </font>
        </div>
    <table class="table">
        <tr>
        <tr style="background-color:Highlight; text-align:center">

            <th>
                <div>Số Điện Thoại</div>
            </th>

            <th>
                <div>Tên Khách Hàng</div>
            </th>
            <th>
                <div>Địa Chỉ</div>
            </th>
            <th>
                <div>Email</div>
            </th>
            <th>
                <div>Mật Khẩu</div>
            </th>
            <th>
                <div>Đã Mua</div>
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.SoDienThoai)

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TenKH)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MatKhau)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DaMua)
                </td>

            </tr>
        }

    </table>
</body>